---
title: "What They Didn't Teach You About Data Science"
format:
  revealjs:
    slide-number: c/t
    width: 1600
    height: 900
    theme: simple
    highlight-style: github
    code-block-border-left: "#4f6952"
    code-block-bg: true
    code-link: true
---

Showing data

```{r}
library(ggplot2)
```


```{r}
#| message: false
#| warning: false
#| echo: fenced

mtcars |>
  dplyr::filter(mpg > 20)

```

## Mermaid

```{mermaid}
graph TD;

    A[Main Branch] --> B1[Jim's Feature Branch]
    A --> B2[Phil's Feature Branch]
    B1 --> C1{Work on Feature}
    B2 --> C2{Work on Feature}
    C1 --> D1[Commit Changes]
    C2 --> D2[Commit Changes]
    D1 --> E1[Push Changes to Jim's Feature Branch]
    D2 --> E2[Push Changes to Phil's Feature Branch]
    E1 --> F1[Create Pull Request]
    E2 --> F2[Create Pull Request]
    F1 --> G1[Review Code]
    F2 --> G2[Review Code]
    G1 --> H1[Approve Changes]
    G2 --> H2[Approve Changes]
    H1 --> I1[Merge Pull Request]
    H2 --> I2[Merge Pull Request]
    I1 --> J1[Delete Jim's Feature Branch]
    I2 --> J2[Delete Phil's Feature Branch]

```

## Fragments

::: {.fragment}
Fade in
:::

::: {.fragment .fade-out}
Fade out
:::

::: {.fragment .highlight-red}
Highlight red
:::

::: {.fragment .fade-in-then-out}
Fade in, then out
:::

## *Advanced* Fragments

::: {.fragment .fade-in}
::: {.fragment .highlight-red}
::: {.fragment .semi-fade-out}
Fade in > Turn red > Semi fade out
:::
:::
:::

# How to order fragments

::: {.fragment fragment-index=3}
Appears last
:::

::: {.fragment fragment-index=1}
Appears first
:::

::: {.fragment fragment-index=2}
Appears second
:::

##

::: {.r-fit-text}
But!
:::

::: {.fragment fragment-index=2}
And that's a big but.
:::

::: {.fragment fragment-index=3}
And I cannot lie.
:::

## Tabsets

::: {.panel-tabset}

## Element 1

```{r}
#| fig-cap: Temperature and ozone level.
#| warning: false
#| message: false
ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess"
)
```